baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: Growlr
primary: true
siteGroup: 45a00e92-2550-47ce-b789-33064e5da296 # Craft CMS Vite Tailwind
sortOrder: 1
