altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  aed645df-ef97-4b8c-900e-4ef6d3401c22:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-29T02:22:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b232111b-f757-4525-880f-9a3496e30501
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a5944e34-dc13-486a-8a95-af1997ef6fa0
        userCondition: null
fs: local
handle: animals
name: Animals
sortOrder: 1
subpath: animals
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
