columnSuffix: null
handle: sex
instructions: null
name: Sex
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Female
        -
          - value
          - female
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Male
        -
          - value
          - male
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
