defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e27725a4-1f5e-4cb7-a977-8aaa9f8146b9 # Page Builder
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  88a82adb-74b9-4d14-b4bf-8e9a26d20d3e: # Growlr
    enabledByDefault: true
    hasUrls: true
    template: homepage/_entry.twig
    uriFormat: __home__
type: single
