defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 360356d7-7d36-4cf2-a063-ebf63125cc00 # Pawmates
handle: pawmates
maxAuthors: 1
name: Pawmates
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  88a82adb-74b9-4d14-b4bf-8e9a26d20d3e: # Growlr
    enabledByDefault: true
    hasUrls: true
    template: pawmates/_entry.twig
    uriFormat: 'pawmates/{slug}'
type: channel
